-- Жанры фильмов
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Комедия');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Драма');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Мультфильм');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Триллер');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Документальный');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Боевик');

-- Рейтинги фильмов (MPA)
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('G');      -- Все возрасты
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('PG');     -- Родители рекомендуется
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('PG-13');  -- 13+
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('R');      -- 17+ ограничение
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('NC-17');  -- 18+