-- Жанры фильмов
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Комедия');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Драма');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Мультфильм');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Триллер');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Документальный');
MERGE INTO GENRES (NAME) KEY(NAME) VALUES ('Боевик');

-- Рейтинги фильмов (MPA)
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('G');      -- Все возрасты
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('PG');     -- Родители рекомендуется
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('PG-13');  -- 13+
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('R');      -- 17+ ограничение
MERGE INTO MPA_RATINGS (NAME) KEY(NAME) VALUES ('NC-17');  -- 18+

-- Пользователи
INSERT INTO USERS (NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES ('Иван Иванов', 'ivan123', 'ivan@example.com', '1990-05-12');

INSERT INTO USERS (NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES ('Петр Петров', 'petr321', 'petr@example.com', '1985-03-08');

-- Фильмы
INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_RATING)
VALUES ('Фильм 1', 'Описание фильма 1', '2000-01-01', 120, 1);

INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_RATING)
VALUES ('Фильм 2', 'Описание фильма 2', '2010-05-15', 90, 2);

-- Лайки
INSERT INTO FILM_LIKES (FILM_ID, USER_ID) VALUES (1, 1);

-- Жанры фильмов
INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (1, 1);
INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (2, 2);

-- Друзья
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS) VALUES (1, 2, TRUE);